### ISSUE TITLE
Nova 4 Support

### ISSUE THREAD

**Issue by bashgeek** [bayareawebpro/nova-field-ckeditor#10]
Nova in version 4 was released last week. Any chance we will see support for this in the near future? :-)

Anything we can do to help?

Thanks!

**Comment by bayareawebpro** [comment]
I started a new `nova-v4` branch but there's a lot of issues that need to be addressed. I don't have an ETA at this time.

I have things partially working, but need to fix some core functionality and provide new css layouts for the modals etc.

I'll update this issue when I have it fully working, I could use some help with CSS at that point if you're interested.

**Comment by rebeccaatwaxeye** [comment]
@bayareawebpro I have "butchered" a forked version that has the core editor working in nova 4, I haven't yet had time to tackle the modals but hopefully it can be helpful?. https://github.com/rebeccaatwaxeye/nova-field-ckeditor/tree/nova-v4

**Comment by bayareawebpro** [comment]
@rebeccaatwaxeye Great thanks, will take a look.

**Comment by pindab0ter** [comment]
I can confirm that basic functionality is working on the `nova-v4`-branch as of now. The only thing that I'm noticing at first glance is that the editor field doesn't have dark mode support yet.

**Comment by bayareawebpro** [comment]
After some lengthy discussions we've decided to move away from Nova in favor of a custom solution.  
 
This repository will be eventually archived in a few months, feel free to fork it and maintain your own version if you would like to continue using it.  

The `master` branch is a self contained build, but only works for Nova3 / Vue2.

The `dev` branch (mostly working, some style issues, Nova4 / Vue3) depends on an NPM package `@bayareawebpro/ckeditor5-classic-custom`, which should also be forked to customize the editor build.
