### ISSUE TITLE
Media Browser not showing files

### ISSUE THREAD

**Issue by JurjenRoels** [bayareawebpro/nova-field-ckeditor#2]
Hi,

when using the FeaturedMedia, I get a modal No images are shown.

When I search for something that is not in the media Table. I get No Results in the modal.

When using a partial of the filename, that is in the media table, I get a blank modal.

I checked the nova-api call that is fired. The file is correctly returned in a json.

Working with larval 8.6.0 with nova 3.10.0

**Comment by bayareawebpro** [comment]
It appears there was a bug with newer versions of Nova where the transition element was hiding the content.  I removed it and it's now working as expected.
