### ISSUE TITLE
format tmp not supported

### ISSUE THREAD

**Issue by mesrack** [bayareawebpro/nova-field-ckeditor#5]
Hi,

When i want create a media with MediaUpload field, i have this error : Encoding format (tmp) is not supported.

How do I get out of this?

Thank you for answering me.

PS: I did not modify the base models

**Comment by bayareawebpro** [comment]
Sounds like an issue with your environment.  I'm not sure how to help you.  The image manipulation is handled by a vendor package.

**Comment by bayareawebpro** [comment]
I researched this a bit more and found an issue with the mime handling of Intervention Image when no filename extension is provided.  I have published a fix for this in the newest release.
