### ISSUE TITLE
Better customization options

### ISSUE THREAD

**Issue by mostafaznv** [bayareawebpro/nova-field-ckeditor#7]
Hi,
I installed this package and it's perfectly fine.

But it would be better if we could translate texts in `media-browser.vue` and also changing api path in `fetch` function in `media-browser.vue`
I decided to change name of `Media` model to `Image` and after that, media-picker couldn't fetch images and got 404 error.

**edit 1**: I need translation for all vue templates
**edit 2**: Is it possible to add color picker, highlighter and font size picker? I see there are a lot of tools that are missing in my toolbar.

**Comment by mostafaznv** [comment]
This package is nice but toolbar items are minimum.
I realized this is classic version of ckeditor.
Is there any way to change it to `Document` mode?
And is there any way to change package direction to `rtl`?

Just look at this picture. toolbar has options like: 
- Font Size
- Font Family
- Font Color
- Font Background
- ...

![download](https://user-images.githubusercontent.com/7619687/129771563-28da458e-349f-463a-a4c2-25aff5bb5e24.jpeg)

**Comment by bayareawebpro** [comment]
This package was designed for my client's requirements.  You are welcome to fork it for your needs.
