### ISSUE TITLE
Laravel Version Requirement

### ISSUE THREAD

**Issue by marktinsley** [bayareawebpro/nova-field-ckeditor#8]
Nova requires Laravel 7+. It looks like this package requires Laravel 8. Is it possible for this package to require Laravel 7+?

**Comment by bayareawebpro** [comment]
I got tired of supporting it, but there's no reason it won't run with 7, you can fork it and update the composer.json and it should work fine.  The older versions support 7, but I made some improvements recently to the JS, so you should fork it and revert the version for the best codebase to maintain.
